### ISSUE TITLE
Compilation fails due to llvm-config missing

### ISSUE THREAD

**Issue by symeonp** [quarkslab/rewind#2]
Hey,

Thank you so much for the project! Just a quick one, trying to compile and getting the following error:

```
C:\Users\symeon\Desktop\rewind\rewind-cli>cargo +nightly build --release
warning: couldn't execute `llvm-config --prefix` (error: Cannot find file. (os error 2))
warning: set the LLVM_CONFIG_PATH environment variable to a valid `llvm-config` executable
   Compiling rewind-whvp v0.1.0 (C:\Users\symeon\Desktop\rewind\rewind-whvp)
   Compiling rewind-system v0.1.0 (C:\Users\symeon\Desktop\rewind\rewind-system)
error[E0425]: cannot find value `WHV_RUN_VP_CANCEL_REASON_WHvRunVpCancelReasonUser` in this scope
    --> rewind-whvp\src\whvp.rs:520:12
     |
520  |     User = WHV_RUN_VP_CANCEL_REASON_WHvRunVpCancelReasonUser as isize,
     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: a constant with a similar name exists: `WHV_RUN_VP_CANCEL_REASON_WhvRunVpCancelReasonUser`
     |
    ::: C:\Users\symeon\Desktop\rewind\target\release\build\whvp-sys-9d4536c1db4309c4\out/whvp_bindings.rs:5658:1
     |
5658 | pub const WHV_RUN_VP_CANCEL_REASON_WhvRunVpCancelReasonUser: WHV_RUN_VP_CANCEL_REASON = 0;
     | ------------------------------------------------------------------------------------------ similarly named constant `WHV_RUN_VP_CANCEL_REASON_WhvRunVpCancelReasonUser` defined here

For more information about this error, try `rustc --explain E0425`.
error: could not compile `rewind-whvp` due to previous error
warning: build failed, waiting for other jobs to finish...
error: build failed
```

I've previously changed the LIBCLANG_PATH to "**C:\Program Files\LLVM\bin**" as per documentation
but interesting enough there's no **llvm-config** on that folder... what am I missing here?

Also, what about the **WHV_RUN_VP_CANCEL_REASON_WHvRunVpCancelReasonUser** function is complaining?

Thanks :)

**Comment by erynian** [comment]
Hello,
Your SDK version is different that the one I'm using. MS changed the case of some functions and the code generated by bindgen is not correct. Can you check if the error is still present with Windows SDK (10.0.19041.0)?

**Comment by symeonp** [comment]
Hello,

Will do thank you! And what about llvm-config that doesn't even ship with the installer?
What's the workaround?

Thanks!

**Comment by erynian** [comment]
Hello,
Sorry for the late response I was on vacation.
You can safely ignore the warning about llvm-config. Just be sure to have the environnement variable `LIBCLANG_PATH` set up correctly 
For example in powershell:
```
> $env:LIBCLANG_PATH="C:\Program Files\LLVM\bin"
```
It is required by bindgen (https://rust-lang.github.io/rust-bindgen/requirements.html)

**Comment by symeonp** [comment]
Hey,

Thanks so much and I hope you have had a nice break.
Now am getting a brand new message, I believe something chnaged with Rust?
Am using the SDK version you mentione earlier:

C:\Users\symeon\source\repos\rewind\rewind-cli>cargo +nightly build
--release
   Compiling serde v1.0.129
   Compiling whvp-sys v0.1.0 (C:\Users\symeon\source\repos\rewind\whvp-sys)
   Compiling bochscpu v0.1.0
(C:\Users\symeon\source\repos\rewind\vendor\bochscpu)
   Compiling color-spantrace v0.1.6
   Compiling clap v3.0.0-beta.4
   Compiling hyper v0.13.10
error[E0557]: feature has been removed
 --> vendor\bochscpu\src\lib.rs:1:12
  |
1 | #![feature(unwind_attributes)]
  |            ^^^^^^^^^^^^^^^^^ feature has been removed
  |
  = note: use the C-unwind ABI instead

   Compiling color-eyre v0.5.11
For more information about this error, try `rustc --explain E0557`.
error: could not compile `bochscpu` due to previous error
warning: build failed, waiting for other jobs to finish...
error: build failed

Thanks

Στις Δευ, 23 Αυγ 2021 στις 3:29 μ.μ., ο/η erynian ***@***.***>
έγραψε:

**Comment by erynian** [comment]
Oh didn't have this one. I need to dig a bit to see what's going on...

**Comment by erynian** [comment]
So this is something related to the merge of unwind ABI in latest rust. I've opened an issue in bochscpu repository (https://github.com/yrp604/bochscpu/issues/3). 
A bad workaround is to remove the line in `vendor\bochscpu\src\lib.rs`. It'll allow the code to compile.
You may encounter another error 
```
error[E0599]: no method named `multiple` found for struct `Arg` in the current scope
   --> rewind-cli\src\cli.rs:834:12
    |
834 |     #[clap(multiple(true), number_of_values(1), parse(try_from_str=parse_hex))]
    |            ^^^^^^^^ method not found in `Arg<'_>`
```

Clap API changed and I need to fix that.
I'll keep you posted

**Comment by erynian** [comment]
Clap error is fixed

**Comment by symeonp** [comment]
Hey,

Can confirm this hack worked! Can't close the issue cause I can't login but
will do once am sorted out!

Thanks so much :)

>
