### ISSUE TITLE
Dump context pykd seems to not get snapshot for me

### ISSUE THREAD

**Issue by symeonp** [quarkslab/rewind#3]
Heya again,

So following your instructions:
```
0: kd> !load pykd
0: kd> !py C:\Users\symeon\Desktop\rewind\scripts\pykd_dump_context.py D:\snapshots

************* Path validation summary **************
Response                         Time (ms)     Location
Deferred                                       srv*c:\symbols*https://msdl.microsoft.com/download/symbols
saving context
saving parameters
saving memory
```
This does not look to be working for me. I have tried with both Windbg Preview and the old x64, yet
the debugger gets stuck with **BUSY** . However, **context.json** and **params.json** both have data, yet the actual **mem.dmp** is empty and I left it running a for a few hours.. any ideas what's going on?

Thanks again!

Edit: Am using **pykd_ext_2.0.0.25** latest version on python **3.9.1** if that helps!

**Comment by erynian** [comment]
The `.dump` operation of WinDBG can be quite long (since it copies all memory pages). Do you use network kernel debugging?

**Comment by symeonp** [comment]
Interesting, yes am using kd.net ..
Let me try one time then.

Thanks!

**Comment by symeonp** [comment]
Closing this issue as it must be my setup..
```
kd> .dump /ka /o D:\snapshots\18362.1.amd64fre.19h1_release.190318-1202\cng\ConfigIoHandler_Safeguarded\mem.dmp
Creating D:\snapshots\18362.1.amd64fre.19h1_release.190318-1202\cng\ConfigIoHandler_Safeguarded\mem.dmp - Active kernel and user memory bitmap dump
Collecting pages to write to the dump. This may take a while.
```
