### ISSUE TITLE
Error("unknown error: missing page 0")

### ISSUE THREAD

**Issue by symeonp** [quarkslab/rewind#7]
Hello,

Just got a snapshot of a potential target, unfortunately am getting the below error when trying to trace it with WHVP:

```
:: Running tracer
==> loading snapshot
==> will use whvp backend
==> setting tracer initial state
rax=0000000000000000 rbx=0000000000000001 rcx=000000000148af10
rdx=00000000c0000000 rsi=0000000000a9b470 rdi=0000000000000000
rip=00007ffbe4a87860 rsp=000000000188ecb8 rbp=000000000148af10
 r8=0000000000000000  r9=000000000188ed08 r10=000000000188edbb
r11=000000000148af46 r12=000000000188ed88 r13=000000000188eda0
r14=0000000000000001 r15=00000000012d1dc0
cs=0033  ss=002b  ds=002b  es=002b  fs=0053  gs=002b  rflags=0246
==> running tracer
==> executed 1356 instruction(s) in 39.8778ms (Error("unknown error: missing page 0"))
==> seen 652 unique address(es)
==> mapped 35 page(s) (143.36 kB)
==> 17 page(s) were modified
```

Also interesting enough, the bochs backend completely hangs on the 'running tracer' phase...
I believe the snapshot is decent as it targets exactly a single function.
Not sure how much I can help you unless I provide you with the snapshot so you can reproduce it?

Thanks

**Comment by erynian** [comment]
Hello,
Your snapshot seems to target an userland function (rip is in userland). It's something that is currently not tested and not supported (the segments are hardcoded for kernel handling).
In the future it's a thing I want to support.
The missing page error indicates that somehow you tried to fetch the first physical page and it was not present in the snapshot.
I need to update the README to reflect this actual limitation.

**Comment by symeonp** [comment]
Yes that's exactly the case! I thought it would be a good idea as I had some targets that I found interesting.

Many thanks though.
